# -*- coding: utf-8 -*-
"""python_31_OlgaZagoruiko_hw_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DGUoPm6QiNr52-ZrYm5AiSAJwUeRCvds

Завантажте цей набір даних рейтингу кави та створіть візуалізації, щоб відповісти на запитання. Ви можете використовувати додаткові типи графіків до тих, які ми дізналися на уроках, якщо ви думаєте, що вони допоможуть відповісти на запитання.

Ви можете знайти опис набору даних тут.
"""

import os.path
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def download_document(file_name, document_url):
    if os.path.exists(file_name):
        pass
    else:
        response=requests.get(document_url)
        if response.status_code==200:
            with open(file_name,'wb') as file:
                file.write(response.content)
        else:
            print(f"Failed to download the document. Status code: {response.status_code}")


file_name='coffee_ratings.csv'
document_url='https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv'

download_document(file_name,document_url)

df_coffee_ratings=pd.read_csv('coffee_ratings.csv')
df_coffee_ratings.drop_duplicates()
print(df_coffee_ratings)

df_coffee_ratings.columns

df_coffee_ratings.info()

df_coffee_ratings[['country_of_origin','number_of_bags']]

df_coffee_ratings['country_of_origin'].unique()

"""### 1. Які країни є великими експортерами кави?"""

df_top_10=df_coffee_ratings.groupby('country_of_origin').agg({'number_of_bags': 'count'}).nlargest(n=10,columns='number_of_bags')
print(df_top_10)

#Будуємо стовпчикову гістограму
plt.figure(figsize=(10,6))
df_top_10.plot(kind = "bar", legend=False, color="green")
plt.title('Top 10 the largest coffee exporters')
plt.xlabel('Countries')
plt.ylabel('Number of bags tested')
plt.show()

# Будуємо лінійчасту гістограмy
df_top_10_2=df_coffee_ratings['country_of_origin'].value_counts().nlargest(n=10)
df_top_10_2.plot(kind = "barh")
plt.title('Top 10 країн найбільших експортерів кави')
plt.xlabel('Частота')
plt.ylabel('Країни')

"""### 2. Які кореляції між різними показниками оцінки кави?

**Кореляційний аналіз** – це статистичне дослідження стохастичної
залежності між випадковими величинами (англ. correlation — взаємозв'язок). У
найпростішому випадку досліджують дві вибірки (набори даних), у загальному
– їх багатовимірні комплекси (групи).
Мета кореляційного аналізу – виявити, чи існує істотна залежність
однієї змінної від інших

Найбільш відомою мірою залежності двох величин є коефіцієнт
кореляції Пірсона. Це лінійний коефіцієнт кореляції, який показує лінійний взаємозв’язок між двома змінними і коливається в межах від -1 до 1.

Проаналізуємо залежність показника оцінки кави "total_cup_point" від наступних показників якості кави:

методу обробки - 'processing_method';
різновиду бобів - 'variety';
сорту аромату -'aroma';
смаку - 'flavor';
ступення кислотності - 'acidity';
сорту тіла - 'body';
сорту балансу - 'balance';
ступення однорідності -'uniformity';
сорту солодкості - 'sweetness' ;
рівня вологи - 'moisture';
кольору бобів - 'color';
"""

df_coffee_features=df_coffee_ratings[['total_cup_points', 'aroma','flavor','acidity','body','balance','uniformity', 'sweetness','moisture']]
print(df_coffee_features)

"""Метод pandas corr() забезпечує простий спосіб обчислення кореляції для датафрейму.
Отримаємо матрицю кореляції
"""

coffee_corr=df_coffee_features.corr(method='pearson')
print(coffee_corr)

"""Візуалізуємо матрицю кореляції між різними показниками оцінки кави  за допомогою теплової карти"""

plt.figure(figsize=(10,6))
sns.heatmap(coffee_corr,annot=True,cmap='coolwarm',fmt='.2f')
plt.title('Кореляційна матриця')
plt.show()

"""**Висновок**: як бачимо оцінка якості кави дуже залежить від таких показників: смаку,  аромату, збалансованості, кислотності. В меншій мірі від: ступення однорідності, солодкості, рівня вологи"""

plt.figure(figsize=(10,6))
sns.heatmap(coffee_corr, annot=True, cmap='crest', vmin=0.65, vmax=1, fmt='.2f', linewidth=.5)
plt.title('Кореляційна матриця')
plt.show()

"""### 3. Який (якщо є) вплив кольору зерен на загальний сорт кави?

'species' - сорт кави;
'color' - колір бобів
"""

df_coffee_ratings['species'].unique()

df_coffee_ratings['color'].unique()

df_new=df_coffee_ratings[['total_cup_points','species','color']]
df_new

df_pilot_table=df_new.pivot_table(index='species', columns='color', values='total_cup_points', aggfunc='mean')
df_pilot_table

plt.figure(figsize=(10,6))
sns.heatmap(df_pilot_table, annot=True, cmap=sns.cubehelix_palette(as_cmap=True),fmt='.2f', linewidth=.5)
plt.title('Теплова карта порівняння середніх значень загальної оцінки для різних комбінацій виду кави та кольору зерен')
plt.show()

plt.figure(figsize=(10,6))
df_pilot_table.plot(kind = "bar", legend=True, color=['tab:blue', 'tab:cyan', 'tab:green'])
plt.title('Стовпчикова діаграма  для порівняння середніх значень загальної оцінки для різних видів кави залежно від кольору')
plt.xlabel('Сорт кави')
plt.ylabel('Середня оцінка кави')

"""Висновок: Суттєво не впливає колір зерен кави на сорт кави

### 4. Чи впливає країна походження на якість кави?
"""

group_country=df_coffee_ratings.groupby('country_of_origin').agg({'total_cup_points': 'mean'})
print(group_country)

plt.figure(figsize=(10,6))
group_country.plot.bar(legend=False)
plt.title('Аналіз впливу країни походження на якість кави')
plt.xlabel('Країна')
plt.ylabel('Середня оцінка кави')
plt.show()

"""Обчислимо кофіцієнт кореляції Спірмена"""

corr_spearman=group_country.corr(method='spearman')
print(corr_spearman)

"""Висновок: країна походження впливає на показник якості кави

### 5. Чи суттєво  впливає висота на якість кави?
"""

df_coffee_ratings[['total_cup_points','altitude_mean_meters']].head(50)

count_nan=df_coffee_ratings['altitude_mean_meters'].isna().sum()
print(f'Кількість пропущених значень в стовпчику "Середня висота над рівнем моря в метрах" {count_nan}')

"""Заповнимо NAN медіанними значеннями"""

df_coffee_ratings['altitude_mean_meters']=df_coffee_ratings['altitude_mean_meters'].fillna(df_coffee_ratings['altitude_mean_meters'].median())

df_coffee_ratings['altitude_mean_meters'].isna().sum()

df_coffee_ratings_altitude=df_coffee_ratings[['total_cup_points','altitude_mean_meters']]
df_coffee_ratings_altitude

"""Позбавимось некоректної висоти"""

df_coffee_ratings_altitude_correct=df_coffee_ratings_altitude[df_coffee_ratings_altitude['altitude_mean_meters']<3500]
df_coffee_ratings_altitude_correct

plt.figure(figsize=(10,8))
sns.relplot(x='altitude_mean_meters', y="total_cup_points", kind="line", data=df_coffee_ratings_altitude_correct)
plt.xlim(-300,2500)
plt.ylim(60,df_coffee_ratings_altitude_correct['total_cup_points'].max())
plt.title('Графік залежності оцінки якості кави від висоти')
plt.show()

"""Висновок:  не можна сказати, що висота над рівнем моря суттєво *впливає* на оцінку якості кави , пряма залежність не прослідковується, різні випадки"""

plt.figure(figsize=(10,8))
sns.kdeplot(df_coffee_ratings_altitude_correct['altitude_mean_meters'], color='r', legend=True)
plt.title('Ядерна оцінка щільності')

plt.xlim(-300,2500)
# plt.ylim(60,df_coffee_ratings_altitude_correct['total_cup_points'].max())

plt.show()